server:
  port: 8081
spring:
  profiles:
    active: spring
---
spring:
  profiles: spring
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:8082/auth/oauth/check_token
          client-id: abcd
          client-secret: qwerty
---
spring:
  profiles: google
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
